version: "3"

services:
  front:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
      - /front/node_modules/
    environment:
      HOST: 0.0.0.0


  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
