# Generated by Django 3.2.12 on 2022-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.JSONField(default=list),
        ),
    ]
